# Generated by Django 4.2.3 on 2023-07-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_n3', '0002_empleado_delete_gerente_delete_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='año',
            new_name='anio',
        ),
    ]
